# Generated by Django 3.1.5 on 2021-01-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20210118_0059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['answer']},
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_type',
            field=models.CharField(choices=[('describe_service', 'describe_service'), ('choose_service', 'choose_service'), ('services', 'services'), ('billing', 'billing'), ('general', 'general')], max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('describe_service', 'describe_service'), ('choose_service', 'choose_service'), ('services', 'services'), ('billing', 'billing'), ('general', 'general')], max_length=255),
        ),
    ]
