# Generated by Django 3.1.5 on 2021-01-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_multiplechoicequestion_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
    ]
