# Generated by Django 3.1.5 on 2021-01-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20210118_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('choice1', models.TextField(blank=True, null=True)),
                ('choice2', models.TextField(blank=True, null=True)),
                ('choice3', models.TextField(blank=True, null=True)),
                ('choice4', models.TextField(blank=True, null=True)),
                ('answers', models.CharField(max_length=255)),
            ],
        ),
    ]
