# Generated by Django 3.1.5 on 2021-01-19 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='answer',
            new_name='description',
        ),
    ]
