# Generated by Django 3.1.5 on 2021-01-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('contact', models.EmailField(max_length=254)),
                ('date_received', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact messages',
                'verbose_name_plural': 'Contact messages',
            },
        ),
    ]
